name: Contexts
version: ${version}
authors: ${authors}

main: cn.chuanwise.contexts.bukkit.ContextsPlugin
api-version: 1.19

#libraries:
#  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.14.0
#  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.14.0

commands:
  contexts: {}
